# spring configuration
spring:

   # devtools - live reload
   devtools:
      liverload:
         enabled: true
         
   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   # message resource(i18n)
   messages:
      always-meesage-format: true
      basename: messages/messages_ko
      encoding: utf-8
      
   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB
         
   # aop(@EnableAspectJAutoProxy)
   aop:
      auto: true
      proxy-target-class: true
      
      
   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.10.51:3306/webdb?characterEncoding=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10 
      
     



# server
server:
   port: 8080
   servlet:
      context-path: /mysite06
      encoding:
         charset: utf-8
         enabled: true

# logging
logging:
   config: classpath:logback.xml
  